// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: create-user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO user (
	Email,
	Hash
) VALUES (
	?,
	?
) RETURNING id
`

type CreateUserParams struct {
	Email string
	Hash  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Hash)
	var id int64
	err := row.Scan(&id)
	return id, err
}
