// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: create-app.sql

package db

import (
	"context"
)

const createApp = `-- name: CreateApp :one
INSERT INTO app (
	Name,
	UserID,
	Type,
	RedirectURI,
	ClientID,
	Hash
) VALUES(
	?,
	?,
	?,
	?,
	?,
	?
) RETURNING id
`

type CreateAppParams struct {
	Name        string
	Userid      int64
	Type        string
	Redirecturi string
	Clientid    interface{}
	Hash        string
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createApp,
		arg.Name,
		arg.Userid,
		arg.Type,
		arg.Redirecturi,
		arg.Clientid,
		arg.Hash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
