// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delete-app.sql

package db

import (
	"context"
)

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM app WHERE ClientID = ? AND UserID = ?
`

type DeleteAppParams struct {
	Clientid interface{}
	Userid   int64
}

func (q *Queries) DeleteApp(ctx context.Context, arg DeleteAppParams) error {
	_, err := q.db.ExecContext(ctx, deleteApp, arg.Clientid, arg.Userid)
	return err
}
