// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: find-user-by-email.sql

package db

import (
	"context"
)

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, hash, created, updated FROM user WHERE Email = ?
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Hash,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
