// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: get-all-apps-by-user.sql

package db

import (
	"context"
)

const getAllAppsByUser = `-- name: GetAllAppsByUser :many
SELECT id, name, userid, type, redirecturi, clientid, hash, created, updated FROM app WHERE UserID = ? ORDER BY CREATED ASC
`

func (q *Queries) GetAllAppsByUser(ctx context.Context, userid int64) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, getAllAppsByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Userid,
			&i.Type,
			&i.Redirecturi,
			&i.Clientid,
			&i.Hash,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
