// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: login.sql

package db

import (
	"context"
)

const login = `-- name: Login :one
SELECT id, email, hash, created, updated FROM user WHERE Email = ? AND Hash = ?
`

type LoginParams struct {
	Email string
	Hash  string
}

func (q *Queries) Login(ctx context.Context, arg LoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, login, arg.Email, arg.Hash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Hash,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
