// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type App struct {
	ID          int64
	Name        string
	Userid      int64
	Type        string
	Redirecturi string
	Clientid    interface{}
	Hash        string
	Created     sql.NullTime
	Updated     sql.NullTime
}

type User struct {
	ID      int64
	Email   string
	Hash    string
	Created sql.NullTime
	Updated sql.NullTime
}
