// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: reset-app-secret.sql

package db

import (
	"context"
)

const resetAppSecret = `-- name: ResetAppSecret :exec
UPDATE app SET Hash=? WHERE ClientID=? AND UserID=?
`

type ResetAppSecretParams struct {
	Hash     string
	Clientid interface{}
	Userid   int64
}

func (q *Queries) ResetAppSecret(ctx context.Context, arg ResetAppSecretParams) error {
	_, err := q.db.ExecContext(ctx, resetAppSecret, arg.Hash, arg.Clientid, arg.Userid)
	return err
}
